title: SÃ­lvio Meireles Blog
description: "My Personal Blog"
author:
  name: "silviomeireles"
  email: "contato@silviomeireles.dev"
  url: "mastersilvio.github.io"
  baseurl: /mastersilvio.github.io

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "silviomeireles"
year : "2019"
